SELECT * FROM COVID_DEATH ORDER BY 3 

SELECT LOCATION , DATE_1 , TOTAL_CASES , NEW_CASES , TOTAL_DEATHS , POPULATION
FROM COVID_DEATH ORDER BY 1 , 2

-----TOTAL CASES VS TOTAL_DEATHS---------
SELECT LOCATION , DATE_1 , TOTAL_CASES , NEW_CASES , TOTAL_DEATHS , (TOTAL_DEATHS/TOTAL_CASES) * 100 AS DEATH_PERCENTAGE 
FROM COVID_DEATH 
WHERE UPPER(LOCATION) LIKE '%STATES%'
AND DATE_1 = TO_DATE('07-18-2021','mm/dd/yyyy')--likelihood of dying if coimg in touch with covid in united states as of 18-07-2021 is 1.78 %

---TOTAL CASES VS POPULATION -----------
SELECT LOCATION , DATE_1 , POPULATION , TOTAL_CASES ,  (TOTAL_CASES/POPULATION) * 100  AS  PERCENT_POPULATION_INFECTED
FROM COVID_DEATH 
WHERE UPPER(LOCATION) LIKE '%STATES%'

----------------------COUNTRY HIGHEST INFECTION RATE COMPARED TO POPULATION -----------------
SELECT LOCATION , POPULATION ,MAX(TOTAL_CASES) AS HIGHEST_INFECTION_COUNT,  MAX((TOTAL_CASES/POPULATION)) * 100  AS  PERCENT_POPULATION_INFECTED 
FROM COVID_DEATH 
WHERE CONTINENT IS NOT NULL --TO EXCLUDE WORLD , ASIA AS COUNTRIES 
GROUP BY lOCATION , POPULATION
HAVING MAX(TOTAL_CASES) IS NOT NULL 
AND MAX((TOTAL_CASES/POPULATION))* 100 IS NOT NULL 
ORDER BY PERCENT_POPULATION_INFECTED DESC 

-----------------------COUNTRY WITH HIGHEST DEATH COUNT PER POPULATION --------------------
SELECT LOCATION , POPULATION ,MAX(CAST (TOTAL_DEATHS AS INT ) ) AS TOTAL_DEATH_COUNT  
FROM COVID_DEATH 
WHERE CONTINENT IS NOT NULL --TO EXCLUDE WORLD , ASIA AS COUNTRIES 
GROUP BY lOCATION , POPULATION 
HAVING MAX(CAST (TOTAL_DEATHS AS INT ) )  IS NOT NULL 
ORDER BY TOTAL_DEATH_COUNT DESC 

----------------CONTINENT WITH HIGHEST DEATH COUNT PER POPULATION------------------

SELECT LOCATION ,MAX(CAST (TOTAL_DEATHS AS INT ) ) AS TOTAL_DEATH_COUNT  
FROM COVID_DEATH 
WHERE CONTINENT IS  NULL --TO INCLUDE WORLD , ASIA AS COUNTRIES 
GROUP BY LOCATION 
HAVING MAX(CAST (TOTAL_DEATHS AS INT ) )  IS NOT NULL 
ORDER BY TOTAL_DEATH_COUNT DESC 

--------------GLOBAL NEW CASES ON A PARTICULAR DAY ------------------------

SELECT DATE_1 , SUM(NEW_CASES)  AS CASES_ON_PARTICULAR_DAY , SUM(CAST (NEW_DEATHS AS INT )) AS DEATHS_ON_PARTICULAR_DAY ,
(SUM(CAST (NEW_DEATHS AS INT )) / SUM(NEW_CASES)  ) * 100 AS DEATH_PERCENATGE
FROM COVID_DEATH
WHERE NEW_DEATHS <> 0--TO AVOID DIVISOR ERROR
GROUP BY DATE_1
HAVING SUM(NEW_CASES) IS NOT NULL 
AND SUM(NEW_DEATHS) IS NOT NULL 
ORDER BY 3 ASC

---------------------------COMBINING COVID_DEATH AND COVID_VACCINATION ----------------
----------------------TOTAL POPULATION VS POPULATION THAT IS VACCINATED -------ADDING UP NEW VACCINATION DAY BY DAY
SELECT DEA.CONTINENT , DEA.DATE_1 , DEA.LOCATION , DEA.POPULATION , VAC.NEW_VACCINATIONS , 
SUM(VAC.NEW_VACCINATIONS)OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION , DEA.DATE_1 ) ROLLING_VACCINATION
--,(ROLLING_VACCINATION/DEA.POPULATION)*100 ----CANNOT BE DONE , CAN BE DONE USING CTE 
FROM COVID_DEATH DEA 
JOIN COVID_VACCINATION VAC ON
DEA.LOCATION = VAC.LOCATION
AND DEA.DATE_1= VAC.DATE_1
AND VAC.NEW_VACCINATIONS IS NOT NULL --TO AVOID NULL VALUES 
WHERE DEA.CONTINENT IS NOT NULL 
ORDER BY 3

------------------------------SOLVING ABOVE CASE USING CTE----------
WITH VACCINATION_VS_POPULATION (CONTINENT , DATE_1 , LOCATION , POPULATION , NEW_VACCINATION , ROLLING_VACCINATION) AS
(SELECT DEA.CONTINENT , DEA.DATE_1 , DEA.LOCATION , DEA.POPULATION , VAC.NEW_VACCINATIONS , 
SUM(VAC.NEW_VACCINATIONS)OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION , DEA.DATE_1 ) ROLLING_VACCINATION
--,(ROLLING_VACCINATION/DEA.POPULATION)*100 ----CANNOT BE DONE , CAN BE DONE USING CTE 
FROM COVID_DEATH DEA 
JOIN COVID_VACCINATION VAC ON
DEA.LOCATION = VAC.LOCATION
AND DEA.DATE_1= VAC.DATE_1
AND VAC.NEW_VACCINATIONS IS NOT NULL --TO AVOID NULL VALUES 
WHERE DEA.CONTINENT IS NOT NULL 
ORDER BY 3) SELECT VACCINATION_VS_POPULATION.* , (ROLLING_VACCINATION/POPULATION)*100  FROM VACCINATION_VS_POPULATION

------------------------------CREATING TEMP TABLE FOR THE ABOVE RESULT ------------------
CREATE TABLE PERCENTAGE_PEOPLE_VACCINATED 
(DATE_1 DATE ,
CONTINENT VARCHAR2(50),
LOCATION VARCHAR2(50),
POPULATION NUMBER,
ROLLING_PEOPLE_VACCINATED NUMBER )

INSERT INTO PPV (CONTINENT , DATE_1 , LOCATION , POPULATION , NEW_VACCINATION , ROLLING_VACCINATION) 
SELECT DEA.CONTINENT , DEA.DATE_1 , DEA.LOCATION , DEA.POPULATION , VAC.NEW_VACCINATIONS , 
SUM(VAC.NEW_VACCINATIONS)OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION , DEA.DATE_1 ) ROLLING_VACCINATION
--,(ROLLING_VACCINATION/DEA.POPULATION)*100 ----CANNOT BE DONE , CAN BE DONE USING CTE 
FROM COVID_DEATH DEA 
JOIN COVID_VACCINATION VAC ON
DEA.LOCATION = VAC.LOCATION
AND DEA.DATE_1= VAC.DATE_1
AND VAC.NEW_VACCINATIONS IS NOT NULL --TO AVOID NULL VALUES 
WHERE DEA.CONTINENT IS NOT NULL ;
-----------------------SELECTING FROM THE INSERTED TABLE ---------------
SELECT * FROM PPV
-----------------------CREATING VIEW ----------------------
CREATE VIEW VIEW_VACCINATION AS 
SELECT DEA.CONTINENT , DEA.DATE_1 , DEA.LOCATION , DEA.POPULATION , VAC.NEW_VACCINATIONS , 
SUM(VAC.NEW_VACCINATIONS)OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION , DEA.DATE_1 ) ROLLING_VACCINATION
--,(ROLLING_VACCINATION/DEA.POPULATION)*100 ----CANNOT BE DONE , CAN BE DONE USING CTE 
FROM COVID_DEATH DEA 
JOIN COVID_VACCINATION VAC ON
DEA.LOCATION = VAC.LOCATION
AND DEA.DATE_1= VAC.DATE_1
AND VAC.NEW_VACCINATIONS IS NOT NULL --TO AVOID NULL VALUES 
WHERE DEA.CONTINENT IS NOT NULL

---------------------KEY INSIGHTS ABOUT COVID CASES------------------------
 
TOTAL NUMBER OF CASES IN USA AS OF 18-07-2021 = 190417528

TOTAL NUMBER OF DEATHS IN USA AS OF 18-07-2021 = 4088864

AS OF 18-07-2021 MOST NUMBER OF CASES ARE FOUND IN ASIA CONTINENT = 59000196

AS OF 18-07-2021 MOST NUMBER OF DEATHS HAPPENED IN EUROPE CONTINENT = 1122542


HIGHEST SINGLE DAY CASES FOUND FOR EACH CONTINENT 

Africa	        26485
South America	115228
Europe	        117900
North America	300462
Asia	        414188










